In [69]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/auto-mpg.data", sep=r'\s+', header=None)
print(data) # 컬럼 명 없음

data.head()

        0  1      2      3       4     5   6  7                          8
0    18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1    15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2    18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3    16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4    17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino
..    ... ..    ...    ...     ...   ...  .. ..                        ...
393  27.0  4  140.0  86.00  2790.0  15.6  82  1            ford mustang gl
394  44.0  4   97.0  52.00  2130.0  24.6  82  2                  vw pickup
395  32.0  4  135.0  84.00  2295.0  11.6  82  1              dodge rampage
396  28.0  4  120.0  79.00  2625.0  18.6  82  1                ford ranger
397  31.0  4  119.0  82.00  2720.0  19.4  82  1                 chevy s-10

[398 rows x 9 columns]

      0  1      2      3       4     5   6  7                          8
0  18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1  15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2  18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3  16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4  17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino

In [70]:
df = pd.DataFrame(data)

df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name']

df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [71]:
label_encoders = {}

columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name']

for column in columns:

    label_encoders[column] = LabelEncoder()

    df[column] = label_encoders[column].fit_transform(df[column])

In [72]:
df.drop("car_name", axis=1)

X = df.drop("mpg", axis=1)
y = df['mpg']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [73]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import classification_report

from sklearn.ensemble import RandomForestClassifier

from sklearn.linear_model import LogisticRegression

from sklearn.neighbors import KNeighborsClassifier

In [74]:
model_dtc = DecisionTreeClassifier()
model_dtc.fit(X_train, y_train)

pred_dtc = model_dtc.predict(X_test)

print(classification_report(y_test, pred_dtc))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           4       0.20      0.50      0.29         2
           5       0.33      0.17      0.22         6
           7       0.17      0.20      0.18         5
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         0
          17       0.50      0.33      0.40         3
          18       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         0
          26       0.00      0.00      0.00         0
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          31       0.00      0.00      0.00         0
          32       0.00      0.00      0.00         1
          33       0.00      0.00      0.00         0
          34       0.00      0.00      0.00         0
          35       0.00      0.00      0.00         0
          36       0.00      0.00      0.00         0
          38       0.00      0.00      0.00         2
          39       0.00      0.00      0.00         1
          40       0.00      0.00      0.00         0
          41       0.00      0.00      0.00         1
          42       0.50      0.50      0.50         2
          44       0.00      0.00      0.00         1
          46       0.00      0.00      0.00         1
          47       0.00      0.00      0.00         1
          48       0.00      0.00      0.00         2
          49       0.00      0.00      0.00         2
          51       0.00      0.00      0.00         0
          53       0.00      0.00      0.00         3
          55       0.00      0.00      0.00         0
          56       0.00      0.00      0.00         0
          58       0.00      0.00      0.00         2
          59       0.00      0.00      0.00         1
          62       0.00      0.00      0.00         0
          63       0.33      0.33      0.33         3
          64       0.00      0.00      0.00         1
          66       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         3
          69       0.00      0.00      0.00         1
          70       0.00      0.00      0.00         0
          72       0.00      0.00      0.00         1
          73       0.00      0.00      0.00         1
          75       0.00      0.00      0.00         0
          76       0.00      0.00      0.00         3
          77       0.00      0.00      0.00         1
          80       0.00      0.00      0.00         0
          84       0.00      0.00      0.00         0
          86       1.00      1.00      1.00         1
          88       0.00      0.00      0.00         0
          89       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          93       0.00      0.00      0.00         0
          95       0.00      0.00      0.00         0
          97       0.00      0.00      0.00         0
          99       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         1
         101       0.00      0.00      0.00         0
         102       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         1
         108       0.00      0.00      0.00         1
         109       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         1
         111       0.00      0.00      0.00         0
         113       0.00      0.00      0.00         0
         114       0.00      0.00      0.00         0
         118       0.00      0.00      0.00         1
         119       0.00      0.00      0.00         0
         120       0.00      0.00      0.00         1
         128       0.00      0.00      0.00         1

    accuracy                           0.09        80
   macro avg       0.04      0.04      0.04        80
weighted avg       0.10      0.09      0.09        80

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [75]:
model_rc = RandomForestClassifier()
model_rc.fit(X_train, y_train)

pred_rc = model_rc.predict(X_test)

print(classification_report(y_test, pred_rc))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           5       0.60      0.50      0.55         6
           7       0.67      0.40      0.50         5
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          17       0.25      0.33      0.29         3
          18       0.00      0.00      0.00         1
          19       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         0
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          30       0.00      0.00      0.00         0
          31       0.00      0.00      0.00         0
          32       0.00      0.00      0.00         1
          33       0.00      0.00      0.00         0
          34       0.00      0.00      0.00         0
          35       0.00      0.00      0.00         0
          36       0.00      0.00      0.00         0
          38       0.00      0.00      0.00         2
          39       0.00      0.00      0.00         1
          41       0.00      0.00      0.00         1
          42       1.00      0.50      0.67         2
          44       0.00      0.00      0.00         1
          46       0.00      0.00      0.00         1
          47       0.00      0.00      0.00         1
          48       0.00      0.00      0.00         2
          49       0.00      0.00      0.00         2
          53       1.00      0.33      0.50         3
          54       0.00      0.00      0.00         0
          55       0.00      0.00      0.00         0
          56       0.00      0.00      0.00         0
          58       0.00      0.00      0.00         2
          59       0.00      0.00      0.00         1
          63       0.25      0.33      0.29         3
          64       0.00      0.00      0.00         1
          66       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         3
          69       0.00      0.00      0.00         1
          70       0.00      0.00      0.00         0
          71       0.00      0.00      0.00         0
          72       0.33      1.00      0.50         1
          73       0.00      0.00      0.00         1
          75       0.00      0.00      0.00         0
          76       0.00      0.00      0.00         3
          77       0.00      0.00      0.00         1
          78       0.00      0.00      0.00         0
          80       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         0
          84       0.00      0.00      0.00         0
          86       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         0
          89       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         0
          95       0.00      0.00      0.00         0
          97       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         1
         102       0.00      0.00      0.00         1
         103       0.00      0.00      0.00         0
         106       0.00      0.00      0.00         0
         107       0.00      0.00      0.00         1
         108       0.50      1.00      0.67         1
         109       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         1
         118       0.00      0.00      0.00         1
         120       0.00      0.00      0.00         1
         128       0.00      0.00      0.00         1

    accuracy                           0.14        80
   macro avg       0.06      0.06      0.05        80
weighted avg       0.18      0.14      0.14        80

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [76]:
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)

pred_lr = model_lr.predict(X_test)

print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           4       0.12      0.50      0.20         2
           5       0.40      0.33      0.36         6
           7       0.00      0.00      0.00         5
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         0
          17       0.17      0.33      0.22         3
          18       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          32       0.00      0.00      0.00         1
          34       0.00      0.00      0.00         0
          36       0.00      0.00      0.00         0
          38       0.00      0.00      0.00         2
          39       0.00      0.00      0.00         1
          40       0.00      0.00      0.00         0
          41       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         2
          44       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         0
          46       0.00      0.00      0.00         1
          47       0.00      0.00      0.00         1
          48       0.00      0.00      0.00         2
          49       0.00      0.00      0.00         2
          53       0.00      0.00      0.00         3
          58       0.20      0.50      0.29         2
          59       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         3
          64       0.00      0.00      0.00         1
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         1
          68       0.20      0.33      0.25         3
          69       0.00      0.00      0.00         1
          71       0.00      0.00      0.00         0
          72       0.00      0.00      0.00         1
          73       0.00      0.00      0.00         1
          74       0.00      0.00      0.00         0
          75       0.00      0.00      0.00         0
          76       0.00      0.00      0.00         3
          77       0.00      0.00      0.00         1
          80       0.00      0.00      0.00         0
          85       0.00      0.00      0.00         0
          86       0.00      0.00      0.00         1
          89       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         0
          95       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         1
         102       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         1
         108       0.33      1.00      0.50         1
         109       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         1
         116       0.00      0.00      0.00         0
         118       0.00      0.00      0.00         1
         120       0.00      0.00      0.00         1
         123       0.00      0.00      0.00         0
         127       0.00      0.00      0.00         0
         128       0.00      0.00      0.00         1

    accuracy                           0.09        80
   macro avg       0.02      0.04      0.03        80
weighted avg       0.06      0.09      0.06        80

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [77]:
model_knn =KNeighborsClassifier()
model_knn.fit(X_train, y_train)

pred_knn = model_knn.predict(X_test)

print(classification_report(y_test, pred_knn))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           4       0.20      0.50      0.29         2
           5       0.43      0.50      0.46         6
           7       0.00      0.00      0.00         5
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         0
          17       0.25      0.33      0.29         3
          18       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          30       0.00      0.00      0.00         0
          32       0.00      0.00      0.00         1
          34       0.00      0.00      0.00         0
          35       0.00      0.00      0.00         0
          38       0.00      0.00      0.00         2
          39       0.00      0.00      0.00         1
          41       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         2
          44       0.00      0.00      0.00         1
          46       0.00      0.00      0.00         1
          47       0.00      0.00      0.00         1
          48       0.00      0.00      0.00         2
          49       0.00      0.00      0.00         2
          52       0.00      0.00      0.00         0
          53       0.00      0.00      0.00         3
          54       0.00      0.00      0.00         0
          56       0.00      0.00      0.00         0
          58       0.17      0.50      0.25         2
          59       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         3
          64       0.00      0.00      0.00         1
          66       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         3
          69       0.00      0.00      0.00         1
          72       0.33      1.00      0.50         1
          73       0.00      0.00      0.00         1
          76       0.00      0.00      0.00         3
          77       0.00      0.00      0.00         1
          80       0.00      0.00      0.00         0
          86       0.00      0.00      0.00         1
          89       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         0
          95       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         1
         102       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         1
         108       0.00      0.00      0.00         1
         109       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         1
         118       0.00      0.00      0.00         1
         120       0.00      0.00      0.00         1
         128       0.00      0.00      0.00         1

    accuracy                           0.09        80
   macro avg       0.02      0.05      0.03        80
weighted avg       0.05      0.09      0.06        80

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))